//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Shared.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class SharedResource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal SharedResource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Shared.Resources.SharedResource", typeof(SharedResource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Accept Terms.
        /// </summary>
        public static string AcceptTerms {
            get {
                return ResourceManager.GetString("AcceptTerms", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Activation Cost.
        /// </summary>
        public static string ActivationCost {
            get {
                return ResourceManager.GetString("ActivationCost", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Address.
        /// </summary>
        public static string Address {
            get {
                return ResourceManager.GetString("Address", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Advanced Search.
        /// </summary>
        public static string AdvancedSearch {
            get {
                return ResourceManager.GetString("AdvancedSearch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AIR PORT TRAFFIC.
        /// </summary>
        public static string AIRPORTTRAFFIC {
            get {
                return ResourceManager.GetString("AIRPORTTRAFFIC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Alert Description.
        /// </summary>
        public static string AlertDescription {
            get {
                return ResourceManager.GetString("AlertDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Alerts.
        /// </summary>
        public static string Alerts {
            get {
                return ResourceManager.GetString("Alerts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All.
        /// </summary>
        public static string All {
            get {
                return ResourceManager.GetString("All", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Apply Charge Value.
        /// </summary>
        public static string ApplyChargeValue {
            get {
                return ResourceManager.GetString("ApplyChargeValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Approved.
        /// </summary>
        public static string Approved {
            get {
                return ResourceManager.GetString("Approved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to عربي.
        /// </summary>
        public static string Arabic {
            get {
                return ResourceManager.GetString("Arabic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Arabic Name.
        /// </summary>
        public static string ArabicName {
            get {
                return ResourceManager.GetString("ArabicName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Assigen To.
        /// </summary>
        public static string AssigenTo {
            get {
                return ResourceManager.GetString("AssigenTo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Avg Speed.
        /// </summary>
        public static string AvgSpeed {
            get {
                return ResourceManager.GetString("AvgSpeed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Battery-Ok.
        /// </summary>
        public static string BatteryOk {
            get {
                return ResourceManager.GetString("BatteryOk", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Begin - End.
        /// </summary>
        public static string Beginend {
            get {
                return ResourceManager.GetString("Beginend", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Birth Date.
        /// </summary>
        public static string Birth_Date {
            get {
                return ResourceManager.GetString("Birth Date", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add.
        /// </summary>
        public static string BtnAdd {
            get {
                return ResourceManager.GetString("BtnAdd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Back.
        /// </summary>
        public static string BtnBack {
            get {
                return ResourceManager.GetString("BtnBack", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Close.
        /// </summary>
        public static string BtnClose {
            get {
                return ResourceManager.GetString("BtnClose", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save.
        /// </summary>
        public static string BtnSave {
            get {
                return ResourceManager.GetString("BtnSave", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cameras.
        /// </summary>
        public static string Cameras {
            get {
                return ResourceManager.GetString("Cameras", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Canceled.
        /// </summary>
        public static string Canceled {
            get {
                return ResourceManager.GetString("Canceled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CARGO.
        /// </summary>
        public static string CARGO {
            get {
                return ResourceManager.GetString("CARGO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  Vehicles History.
        /// </summary>
        public static string CarHistory {
            get {
                return ResourceManager.GetString("CarHistory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Carried Weight.
        /// </summary>
        public static string CarriedWeight {
            get {
                return ResourceManager.GetString("CarriedWeight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Carrier detailed.
        /// </summary>
        public static string Carrierdetailed {
            get {
                return ResourceManager.GetString("Carrierdetailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CarrierDetails.
        /// </summary>
        public static string CarrierDetails {
            get {
                return ResourceManager.GetString("CarrierDetails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Carrier ID.
        /// </summary>
        public static string CarrierID {
            get {
                return ResourceManager.GetString("CarrierID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Catalog Value.
        /// </summary>
        public static string CatalogValue {
            get {
                return ResourceManager.GetString("CatalogValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Charge Value.
        /// </summary>
        public static string ChargeValue {
            get {
                return ResourceManager.GetString("ChargeValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chassis Number.
        /// </summary>
        public static string Chassis_Number {
            get {
                return ResourceManager.GetString("Chassis Number", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chassis Number.
        /// </summary>
        public static string ChassisNumber {
            get {
                return ResourceManager.GetString("ChassisNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CHAT.
        /// </summary>
        public static string CHAT {
            get {
                return ResourceManager.GetString("CHAT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Choose Work Shifts.
        /// </summary>
        public static string Choose_Work_Shifts {
            get {
                return ResourceManager.GetString("Choose Work Shifts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Choose City.
        /// </summary>
        public static string ChooseCity {
            get {
                return ResourceManager.GetString("ChooseCity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Choose Company Branch.
        /// </summary>
        public static string ChooseCompanyBranch {
            get {
                return ResourceManager.GetString("ChooseCompanyBranch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Choose Contractor Types.
        /// </summary>
        public static string ChooseContractorTypes {
            get {
                return ResourceManager.GetString("ChooseContractorTypes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Choose Contract Status.
        /// </summary>
        public static string ChooseContractStatus {
            get {
                return ResourceManager.GetString("ChooseContractStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Choose Country.
        /// </summary>
        public static string ChooseCountry {
            get {
                return ResourceManager.GetString("ChooseCountry", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Choose Customer.
        /// </summary>
        public static string ChooseCustomer {
            get {
                return ResourceManager.GetString("ChooseCustomer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Choose Customer Type.
        /// </summary>
        public static string ChooseCustomerType {
            get {
                return ResourceManager.GetString("ChooseCustomerType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Choose Department.
        /// </summary>
        public static string ChooseDepartment {
            get {
                return ResourceManager.GetString("ChooseDepartment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Choose District.
        /// </summary>
        public static string ChooseDistrict {
            get {
                return ResourceManager.GetString("ChooseDistrict", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Choose Driver.
        /// </summary>
        public static string ChooseDriver {
            get {
                return ResourceManager.GetString("ChooseDriver", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Choose Educational Degree.
        /// </summary>
        public static string ChooseEducationalDegree {
            get {
                return ResourceManager.GetString("ChooseEducationalDegree", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Choose Employee.
        /// </summary>
        public static string ChooseEmployee {
            get {
                return ResourceManager.GetString("ChooseEmployee", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Choose Fixed Asset Type.
        /// </summary>
        public static string ChooseFixedAssetType {
            get {
                return ResourceManager.GetString("ChooseFixedAssetType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Choose Gender.
        /// </summary>
        public static string ChooseGender {
            get {
                return ResourceManager.GetString("ChooseGender", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Choose Group.
        /// </summary>
        public static string ChooseGroup {
            get {
                return ResourceManager.GetString("ChooseGroup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Choose Job Title.
        /// </summary>
        public static string ChooseJobTitle {
            get {
                return ResourceManager.GetString("ChooseJobTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Choose Manager.
        /// </summary>
        public static string ChooseManager {
            get {
                return ResourceManager.GetString("ChooseManager", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Choose Model Maker.
        /// </summary>
        public static string ChoosemodelMaker {
            get {
                return ResourceManager.GetString("ChoosemodelMaker", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Choose Nationality.
        /// </summary>
        public static string ChooseNationality {
            get {
                return ResourceManager.GetString("ChooseNationality", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Choose Page Type.
        /// </summary>
        public static string ChoosePageType {
            get {
                return ResourceManager.GetString("ChoosePageType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Choose Periority.
        /// </summary>
        public static string ChoosePeriority {
            get {
                return ResourceManager.GetString("ChoosePeriority", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Choose Purchaser.
        /// </summary>
        public static string ChoosePurchaser {
            get {
                return ResourceManager.GetString("ChoosePurchaser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Choose Recurring Cost Amount.
        /// </summary>
        public static string ChooseRecurringCostAmount {
            get {
                return ResourceManager.GetString("ChooseRecurringCostAmount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Choose Task Type.
        /// </summary>
        public static string ChooseTaskType {
            get {
                return ResourceManager.GetString("ChooseTaskType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Choose Vehicle.
        /// </summary>
        public static string ChooseVehicle {
            get {
                return ResourceManager.GetString("ChooseVehicle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Choose Vehicle Model.
        /// </summary>
        public static string ChooseVehicleModel {
            get {
                return ResourceManager.GetString("ChooseVehicleModel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Choose Vendor.
        /// </summary>
        public static string ChooseVendor {
            get {
                return ResourceManager.GetString("ChooseVendor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cities.
        /// </summary>
        public static string Cities {
            get {
                return ResourceManager.GetString("Cities", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to City.
        /// </summary>
        public static string City {
            get {
                return ResourceManager.GetString("City", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Closed.
        /// </summary>
        public static string Closed {
            get {
                return ResourceManager.GetString("Closed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CO2 Emissions.
        /// </summary>
        public static string CO2Emissions {
            get {
                return ResourceManager.GetString("CO2Emissions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Code.
        /// </summary>
        public static string Code {
            get {
                return ResourceManager.GetString("Code", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Company Branch.
        /// </summary>
        public static string CompanyBranch {
            get {
                return ResourceManager.GetString("CompanyBranch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Company Branches.
        /// </summary>
        public static string CompanyBranches {
            get {
                return ResourceManager.GetString("CompanyBranches", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Configuration.
        /// </summary>
        public static string Configuration {
            get {
                return ResourceManager.GetString("Configuration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contract End Date.
        /// </summary>
        public static string ContractEndDate {
            get {
                return ResourceManager.GetString("ContractEndDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contract Expiration Date.
        /// </summary>
        public static string ContractExpirationDate {
            get {
                return ResourceManager.GetString("ContractExpirationDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contractors Types.
        /// </summary>
        public static string ContractorsTypes {
            get {
                return ResourceManager.GetString("ContractorsTypes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contractor Type.
        /// </summary>
        public static string ContractorType {
            get {
                return ResourceManager.GetString("ContractorType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contract Reference.
        /// </summary>
        public static string ContractReference {
            get {
                return ResourceManager.GetString("ContractReference", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contracts.
        /// </summary>
        public static string Contracts {
            get {
                return ResourceManager.GetString("Contracts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contract Start Date.
        /// </summary>
        public static string ContractStartDate {
            get {
                return ResourceManager.GetString("ContractStartDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contract Status.
        /// </summary>
        public static string ContractStatus {
            get {
                return ResourceManager.GetString("ContractStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contract Type.
        /// </summary>
        public static string ContractType {
            get {
                return ResourceManager.GetString("ContractType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cost.
        /// </summary>
        public static string Cost {
            get {
                return ResourceManager.GetString("Cost", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cost Description .
        /// </summary>
        public static string CostDescription {
            get {
                return ResourceManager.GetString("CostDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Costs.
        /// </summary>
        public static string Costs {
            get {
                return ResourceManager.GetString("Costs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Countries.
        /// </summary>
        public static string Countries {
            get {
                return ResourceManager.GetString("Countries", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Countries , Cities &amp; Districts.
        /// </summary>
        public static string CountriesCitiesDistricts {
            get {
                return ResourceManager.GetString("CountriesCitiesDistricts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Country.
        /// </summary>
        public static string Country {
            get {
                return ResourceManager.GetString("Country", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to $.
        /// </summary>
        public static string Currency {
            get {
                return ResourceManager.GetString("Currency", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Custom date range.
        /// </summary>
        public static string Customdaterange {
            get {
                return ResourceManager.GetString("Customdaterange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Customer.
        /// </summary>
        public static string Customer {
            get {
                return ResourceManager.GetString("Customer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Customer Contantcs.
        /// </summary>
        public static string CustomerContantcs {
            get {
                return ResourceManager.GetString("CustomerContantcs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Customers.
        /// </summary>
        public static string Customers {
            get {
                return ResourceManager.GetString("Customers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Customer Type.
        /// </summary>
        public static string CustomerType {
            get {
                return ResourceManager.GetString("CustomerType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Daily.
        /// </summary>
        public static string Daily {
            get {
                return ResourceManager.GetString("Daily", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dashboard.
        /// </summary>
        public static string Dashboard {
            get {
                return ResourceManager.GetString("Dashboard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Data Saved Successfully.
        /// </summary>
        public static string DataSavedSuccessfully {
            get {
                return ResourceManager.GetString("DataSavedSuccessfully", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date.
        /// </summary>
        public static string Date {
            get {
                return ResourceManager.GetString("Date", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date Range.
        /// </summary>
        public static string DateRange {
            get {
                return ResourceManager.GetString("DateRange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delay For.
        /// </summary>
        public static string DelayFor {
            get {
                return ResourceManager.GetString("DelayFor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete Confirmation.
        /// </summary>
        public static string Delete_Confirmation {
            get {
                return ResourceManager.GetString("Delete Confirmation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error on deleting this item , please try again.
        /// </summary>
        public static string DeleteErrorMsg {
            get {
                return ResourceManager.GetString("DeleteErrorMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delivery Time Of Orders.
        /// </summary>
        public static string DeliveryTimeOfOrders {
            get {
                return ResourceManager.GetString("DeliveryTimeOfOrders", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Departing at.
        /// </summary>
        public static string DepartingAt {
            get {
                return ResourceManager.GetString("DepartingAt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Department.
        /// </summary>
        public static string Department {
            get {
                return ResourceManager.GetString("Department", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Departments.
        /// </summary>
        public static string Departments {
            get {
                return ResourceManager.GetString("Departments", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Description.
        /// </summary>
        public static string Description {
            get {
                return ResourceManager.GetString("Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Detailed Activity.
        /// </summary>
        public static string DetailedActivity {
            get {
                return ResourceManager.GetString("DetailedActivity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to details of notification.
        /// </summary>
        public static string detailsofnotification {
            get {
                return ResourceManager.GetString("detailsofnotification", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Distance.
        /// </summary>
        public static string Distance {
            get {
                return ResourceManager.GetString("Distance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Distance Traveled.
        /// </summary>
        public static string DistanceTraveled {
            get {
                return ResourceManager.GetString("DistanceTraveled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Distance Travelled.
        /// </summary>
        public static string DistanceTravelled {
            get {
                return ResourceManager.GetString("DistanceTravelled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to District.
        /// </summary>
        public static string District {
            get {
                return ResourceManager.GetString("District", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Districts.
        /// </summary>
        public static string Districts {
            get {
                return ResourceManager.GetString("Districts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Domain.
        /// </summary>
        public static string Domain {
            get {
                return ResourceManager.GetString("Domain", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Doors.
        /// </summary>
        public static string Doors {
            get {
                return ResourceManager.GetString("Doors", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Drag and drop or select add Image.
        /// </summary>
        public static string Drag_and_drop_or_select_add_Image {
            get {
                return ResourceManager.GetString("Drag and drop or select add Image", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Driver Name.
        /// </summary>
        public static string DriverName {
            get {
                return ResourceManager.GetString("DriverName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit.
        /// </summary>
        public static string Edit {
            get {
                return ResourceManager.GetString("Edit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Educational Degree.
        /// </summary>
        public static string EducationalDegree {
            get {
                return ResourceManager.GetString("EducationalDegree", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email.
        /// </summary>
        public static string Email {
            get {
                return ResourceManager.GetString("Email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Employee.
        /// </summary>
        public static string Employee {
            get {
                return ResourceManager.GetString("Employee", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Employees.
        /// </summary>
        public static string Employees {
            get {
                return ResourceManager.GetString("Employees", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to End.
        /// </summary>
        public static string End {
            get {
                return ResourceManager.GetString("End", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to End Date.
        /// </summary>
        public static string EndDate {
            get {
                return ResourceManager.GetString("EndDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contract End Date Must Be Greater Than Start Date.
        /// </summary>
        public static string EndDateMustBeGreaterThanStartDate {
            get {
                return ResourceManager.GetString("EndDateMustBeGreaterThanStartDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to End Location.
        /// </summary>
        public static string endlocation {
            get {
                return ResourceManager.GetString("endlocation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to English.
        /// </summary>
        public static string English {
            get {
                return ResourceManager.GetString("English", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to English Name.
        /// </summary>
        public static string EnglishName {
            get {
                return ResourceManager.GetString("EnglishName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error occured trya gain.
        /// </summary>
        public static string Erroroccuredtryagain {
            get {
                return ResourceManager.GetString("Erroroccuredtryagain", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contract Expiration Date Must Be Greater Than Contract End Date.
        /// </summary>
        public static string ExpirationDateMustBeGreaterThanEndDate {
            get {
                return ResourceManager.GetString("ExpirationDateMustBeGreaterThanEndDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Expired.
        /// </summary>
        public static string Expired {
            get {
                return ResourceManager.GetString("Expired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fax.
        /// </summary>
        public static string Fax {
            get {
                return ResourceManager.GetString("Fax", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ferry Arrival.
        /// </summary>
        public static string FerryArrival {
            get {
                return ResourceManager.GetString("FerryArrival", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Finished.
        /// </summary>
        public static string Finished {
            get {
                return ResourceManager.GetString("Finished", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to First.
        /// </summary>
        public static string First {
            get {
                return ResourceManager.GetString("First", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to First log time.
        /// </summary>
        public static string Firstlogtime {
            get {
                return ResourceManager.GetString("Firstlogtime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fixed Assets.
        /// </summary>
        public static string FixedAssets {
            get {
                return ResourceManager.GetString("FixedAssets", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fixed Asset Type.
        /// </summary>
        public static string FixedAssetType {
            get {
                return ResourceManager.GetString("FixedAssetType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fixed Asset Types.
        /// </summary>
        public static string FixedAssetTypes {
            get {
                return ResourceManager.GetString("FixedAssetTypes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to for Vehice.
        /// </summary>
        public static string forVehice {
            get {
                return ResourceManager.GetString("forVehice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to From.
        /// </summary>
        public static string From {
            get {
                return ResourceManager.GetString("From", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to From Last Hour.
        /// </summary>
        public static string FromLastHour {
            get {
                return ResourceManager.GetString("FromLastHour", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to From Last Month.
        /// </summary>
        public static string FromLastMonth {
            get {
                return ResourceManager.GetString("FromLastMonth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to From Station.
        /// </summary>
        public static string FromStation {
            get {
                return ResourceManager.GetString("FromStation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gender.
        /// </summary>
        public static string Gender {
            get {
                return ResourceManager.GetString("Gender", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Geofence.
        /// </summary>
        public static string Geofence {
            get {
                return ResourceManager.GetString("Geofence", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Geofence Alert.
        /// </summary>
        public static string Geofencealert {
            get {
                return ResourceManager.GetString("Geofencealert", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Give Group All Permissions.
        /// </summary>
        public static string GiveGroupAllPermissions {
            get {
                return ResourceManager.GetString("GiveGroupAllPermissions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Graphical Dashboard.
        /// </summary>
        public static string GraphicalDashboard {
            get {
                return ResourceManager.GetString("GraphicalDashboard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Group.
        /// </summary>
        public static string Group {
            get {
                return ResourceManager.GetString("Group", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Groups.
        /// </summary>
        public static string Groups {
            get {
                return ResourceManager.GetString("Groups", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Has Tracking.
        /// </summary>
        public static string HasTracking {
            get {
                return ResourceManager.GetString("HasTracking", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hide.
        /// </summary>
        public static string Hide {
            get {
                return ResourceManager.GetString("Hide", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Home.
        /// </summary>
        public static string Home {
            get {
                return ResourceManager.GetString("Home", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Horse Power.
        /// </summary>
        public static string HorsePower {
            get {
                return ResourceManager.GetString("HorsePower", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Horse Power Taxation.
        /// </summary>
        public static string HorsePowerTaxation {
            get {
                return ResourceManager.GetString("HorsePowerTaxation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ID Number.
        /// </summary>
        public static string ID_Number {
            get {
                return ResourceManager.GetString("ID Number", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Idle Vehicles.
        /// </summary>
        public static string IdleCars {
            get {
                return ResourceManager.GetString("IdleCars", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Idle Vehicles.
        /// </summary>
        public static string IdleVehicles {
            get {
                return ResourceManager.GetString("IdleVehicles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ignition Alert.
        /// </summary>
        public static string IgnitionAlert {
            get {
                return ResourceManager.GetString("IgnitionAlert", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Image.
        /// </summary>
        public static string Image {
            get {
                return ResourceManager.GetString("Image", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to IMEI.
        /// </summary>
        public static string IMEI {
            get {
                return ResourceManager.GetString("IMEI", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Immatriculation Date.
        /// </summary>
        public static string ImmatriculationDate {
            get {
                return ResourceManager.GetString("ImmatriculationDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to In Proccess.
        /// </summary>
        public static string InProccess {
            get {
                return ResourceManager.GetString("InProccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to In Progress.
        /// </summary>
        public static string InProgress {
            get {
                return ResourceManager.GetString("InProgress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid Logs.
        /// </summary>
        public static string InvalidLogs {
            get {
                return ResourceManager.GetString("InvalidLogs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invoice Date.
        /// </summary>
        public static string InvoiceDate {
            get {
                return ResourceManager.GetString("InvoiceDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invoice Reference.
        /// </summary>
        public static string InvoiceReference {
            get {
                return ResourceManager.GetString("InvoiceReference", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Is Active.
        /// </summary>
        public static string IsActive {
            get {
                return ResourceManager.GetString("IsActive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Items.
        /// </summary>
        public static string Items {
            get {
                return ResourceManager.GetString("Items", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Job Title.
        /// </summary>
        public static string JobTitle {
            get {
                return ResourceManager.GetString("JobTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Key.
        /// </summary>
        public static string Key {
            get {
                return ResourceManager.GetString("Key", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last.
        /// </summary>
        public static string Last {
            get {
                return ResourceManager.GetString("Last", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last Log Processed.
        /// </summary>
        public static string LastLogProcessed {
            get {
                return ResourceManager.GetString("LastLogProcessed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last log time.
        /// </summary>
        public static string Lastlogtime {
            get {
                return ResourceManager.GetString("Lastlogtime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last Odometer.
        /// </summary>
        public static string LastOdometer {
            get {
                return ResourceManager.GetString("LastOdometer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last seen.
        /// </summary>
        public static string LastSeen {
            get {
                return ResourceManager.GetString("LastSeen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last Status.
        /// </summary>
        public static string LastStatus {
            get {
                return ResourceManager.GetString("LastStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last week.
        /// </summary>
        public static string Lastweek {
            get {
                return ResourceManager.GetString("Lastweek", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to License Plate.
        /// </summary>
        public static string LicensePlate {
            get {
                return ResourceManager.GetString("LicensePlate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Liter.
        /// </summary>
        public static string Liter {
            get {
                return ResourceManager.GetString("Liter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Live Dashboard.
        /// </summary>
        public static string LiveDashboard {
            get {
                return ResourceManager.GetString("LiveDashboard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Location.
        /// </summary>
        public static string Location {
            get {
                return ResourceManager.GetString("Location", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LogIn.
        /// </summary>
        public static string LogIn {
            get {
                return ResourceManager.GetString("LogIn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Logo.
        /// </summary>
        public static string Logo {
            get {
                return ResourceManager.GetString("Logo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Log out.
        /// </summary>
        public static string Logout {
            get {
                return ResourceManager.GetString("Logout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lookup items.
        /// </summary>
        public static string LookUpItems {
            get {
                return ResourceManager.GetString("LookUpItems", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lookups.
        /// </summary>
        public static string LookUps {
            get {
                return ResourceManager.GetString("LookUps", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Low battery.
        /// </summary>
        public static string Lowbattery {
            get {
                return ResourceManager.GetString("Lowbattery", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Low fuel.
        /// </summary>
        public static string Lowfuel {
            get {
                return ResourceManager.GetString("Lowfuel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Peringatan remanufaktur hilang.
        /// </summary>
        public static string maintenanceAlertBody {
            get {
                return ResourceManager.GetString("maintenanceAlertBody", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MAIN WIDGET.
        /// </summary>
        public static string MAINWIDGET {
            get {
                return ResourceManager.GetString("MAINWIDGET", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Manager.
        /// </summary>
        public static string Manager {
            get {
                return ResourceManager.GetString("Manager", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Max Speed.
        /// </summary>
        public static string MaxSpeed {
            get {
                return ResourceManager.GetString("MaxSpeed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Minimum Charges.
        /// </summary>
        public static string MinimumCharges {
            get {
                return ResourceManager.GetString("MinimumCharges", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mobile.
        /// </summary>
        public static string Mobile {
            get {
                return ResourceManager.GetString("Mobile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Model Maker.
        /// </summary>
        public static string modelMaker {
            get {
                return ResourceManager.GetString("modelMaker", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Model Makers.
        /// </summary>
        public static string ModelMakers {
            get {
                return ResourceManager.GetString("ModelMakers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Model Year.
        /// </summary>
        public static string ModelYear {
            get {
                return ResourceManager.GetString("ModelYear", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Module.
        /// </summary>
        public static string Module {
            get {
                return ResourceManager.GetString("Module", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Monitor Employees.
        /// </summary>
        public static string MonitorEmployees {
            get {
                return ResourceManager.GetString("MonitorEmployees", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Monthly.
        /// </summary>
        public static string Monthly {
            get {
                return ResourceManager.GetString("Monthly", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Moved Hours.
        /// </summary>
        public static string movedhours {
            get {
                return ResourceManager.GetString("movedhours", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Moving Avarage.
        /// </summary>
        public static string MovingAvarage {
            get {
                return ResourceManager.GetString("MovingAvarage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Moving Vehicles.
        /// </summary>
        public static string MovingCars {
            get {
                return ResourceManager.GetString("MovingCars", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to My Profile.
        /// </summary>
        public static string MyProfile {
            get {
                return ResourceManager.GetString("MyProfile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        public static string Name {
            get {
                return ResourceManager.GetString("Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nationalities.
        /// </summary>
        public static string Nationality {
            get {
                return ResourceManager.GetString("Nationality", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Need Approval.
        /// </summary>
        public static string NeedApproval {
            get {
                return ResourceManager.GetString("NeedApproval", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New.
        /// </summary>
        public static string New {
            get {
                return ResourceManager.GetString("New", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Next.
        /// </summary>
        public static string Next {
            get {
                return ResourceManager.GetString("Next", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No.
        /// </summary>
        public static string No {
            get {
                return ResourceManager.GetString("No", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No data available in table.
        /// </summary>
        public static string Nodataavailableintable {
            get {
                return ResourceManager.GetString("Nodataavailableintable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No.
        /// </summary>
        public static string None {
            get {
                return ResourceManager.GetString("None", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Normal Search.
        /// </summary>
        public static string Normal_Search {
            get {
                return ResourceManager.GetString("Normal Search", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Normal Search.
        /// </summary>
        public static string NormalSearch {
            get {
                return ResourceManager.GetString("NormalSearch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Inserted Value Is Not Valid.
        /// </summary>
        public static string NotValid {
            get {
                return ResourceManager.GetString("NotValid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Not Valid Charge Value.
        /// </summary>
        public static string NotValidChargeValue {
            get {
                return ResourceManager.GetString("NotValidChargeValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Not valid email.
        /// </summary>
        public static string NotValidEmail {
            get {
                return ResourceManager.GetString("NotValidEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Number Of Contract.
        /// </summary>
        public static string NumberOfContract {
            get {
                return ResourceManager.GetString("NumberOfContract", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reports Number.
        /// </summary>
        public static string NumberOfReports {
            get {
                return ResourceManager.GetString("NumberOfReports", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Numbers Only.
        /// </summary>
        public static string Numbers_Only {
            get {
                return ResourceManager.GetString("Numbers Only", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Odometer At Creation.
        /// </summary>
        public static string OdometerAtCreation {
            get {
                return ResourceManager.GetString("OdometerAtCreation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Odometer Type.
        /// </summary>
        public static string OdometerType {
            get {
                return ResourceManager.GetString("OdometerType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Odometer Value.
        /// </summary>
        public static string OdometerValue {
            get {
                return ResourceManager.GetString("OdometerValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Offline.
        /// </summary>
        public static string Offline {
            get {
                return ResourceManager.GetString("Offline", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Online.
        /// </summary>
        public static string Online {
            get {
                return ResourceManager.GetString("Online", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Overall result.
        /// </summary>
        public static string Overallresult {
            get {
                return ResourceManager.GetString("Overallresult", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Over speed.
        /// </summary>
        public static string Overspeed {
            get {
                return ResourceManager.GetString("Overspeed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Weight.
        /// </summary>
        public static string overWeight {
            get {
                return ResourceManager.GetString("overWeight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pages.
        /// </summary>
        public static string Pages {
            get {
                return ResourceManager.GetString("Pages", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PagesTypes.
        /// </summary>
        public static string PagesTypes {
            get {
                return ResourceManager.GetString("PagesTypes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password.
        /// </summary>
        public static string Password {
            get {
                return ResourceManager.GetString("Password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Periority.
        /// </summary>
        public static string Periority {
            get {
                return ResourceManager.GetString("Periority", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Permissions.
        /// </summary>
        public static string Permissions {
            get {
                return ResourceManager.GetString("Permissions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Phone.
        /// </summary>
        public static string Phone {
            get {
                return ResourceManager.GetString("Phone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Planned Start Date.
        /// </summary>
        public static string PlannedStartDate {
            get {
                return ResourceManager.GetString("PlannedStartDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Power.
        /// </summary>
        public static string Power {
            get {
                return ResourceManager.GetString("Power", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Prev.
        /// </summary>
        public static string Prev {
            get {
                return ResourceManager.GetString("Prev", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Previous.
        /// </summary>
        public static string Previous {
            get {
                return ResourceManager.GetString("Previous", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Previous days.
        /// </summary>
        public static string Previousdays {
            get {
                return ResourceManager.GetString("Previousdays", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to previous x days.
        /// </summary>
        public static string previousxdays {
            get {
                return ResourceManager.GetString("previousxdays", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Price.
        /// </summary>
        public static string Price {
            get {
                return ResourceManager.GetString("Price", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Price Liter.
        /// </summary>
        public static string PricePerLiter {
            get {
                return ResourceManager.GetString("PricePerLiter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Purchase.
        /// </summary>
        public static string Purchase {
            get {
                return ResourceManager.GetString("Purchase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Purchaser.
        /// </summary>
        public static string Purchaser {
            get {
                return ResourceManager.GetString("Purchaser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Purchasers.
        /// </summary>
        public static string Purchasers {
            get {
                return ResourceManager.GetString("Purchasers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to RAKEB.
        /// </summary>
        public static string RAKEB {
            get {
                return ResourceManager.GetString("RAKEB", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rate.
        /// </summary>
        public static string Rate {
            get {
                return ResourceManager.GetString("Rate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Recurring Cost Amount.
        /// </summary>
        public static string RecurringCostAmount {
            get {
                return ResourceManager.GetString("RecurringCostAmount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remember Me.
        /// </summary>
        public static string RememberMe {
            get {
                return ResourceManager.GetString("RememberMe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove.
        /// </summary>
        public static string Remove {
            get {
                return ResourceManager.GetString("Remove", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reports.
        /// </summary>
        public static string Reports {
            get {
                return ResourceManager.GetString("Reports", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to this field is required.
        /// </summary>
        public static string Required {
            get {
                return ResourceManager.GetString("Required", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reset Group Permissions.
        /// </summary>
        public static string ResetGroupPermissions {
            get {
                return ResourceManager.GetString("ResetGroupPermissions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Residual Value.
        /// </summary>
        public static string ResidualValue {
            get {
                return ResourceManager.GetString("ResidualValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Robbery.
        /// </summary>
        public static string robbery {
            get {
                return ResourceManager.GetString("robbery", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Screens.
        /// </summary>
        public static string Screens {
            get {
                return ResourceManager.GetString("Screens", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search.
        /// </summary>
        public static string Search {
            get {
                return ResourceManager.GetString("Search", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search About Location.
        /// </summary>
        public static string SearchAboutLocation {
            get {
                return ResourceManager.GetString("SearchAboutLocation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search By.
        /// </summary>
        public static string SearchBy {
            get {
                return ResourceManager.GetString("SearchBy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search Here.
        /// </summary>
        public static string SearchHere {
            get {
                return ResourceManager.GetString("SearchHere", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search Menu.
        /// </summary>
        public static string SearchMenu {
            get {
                return ResourceManager.GetString("SearchMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Seats.
        /// </summary>
        public static string Seats {
            get {
                return ResourceManager.GetString("Seats", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to See All Notification.
        /// </summary>
        public static string SeeNotification {
            get {
                return ResourceManager.GetString("SeeNotification", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select Image.
        /// </summary>
        public static string Select_Image {
            get {
                return ResourceManager.GetString("Select Image", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select All.
        /// </summary>
        public static string SelectAll {
            get {
                return ResourceManager.GetString("SelectAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select Date.
        /// </summary>
        public static string SelectDate {
            get {
                return ResourceManager.GetString("SelectDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select Fuel Type.
        /// </summary>
        public static string SelectFuelType {
            get {
                return ResourceManager.GetString("SelectFuelType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select Service.
        /// </summary>
        public static string SelectService {
            get {
                return ResourceManager.GetString("SelectService", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select Service Type.
        /// </summary>
        public static string SelectServiceType {
            get {
                return ResourceManager.GetString("SelectServiceType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select Transmission Type.
        /// </summary>
        public static string SelectTransmissionType {
            get {
                return ResourceManager.GetString("SelectTransmissionType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select Vehicle.
        /// </summary>
        public static string SelectVehicle {
            get {
                return ResourceManager.GetString("SelectVehicle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Service.
        /// </summary>
        public static string Service {
            get {
                return ResourceManager.GetString("Service", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Services.
        /// </summary>
        public static string Services {
            get {
                return ResourceManager.GetString("Services", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Service Type.
        /// </summary>
        public static string ServiceType {
            get {
                return ResourceManager.GetString("ServiceType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show Alerts.
        /// </summary>
        public static string ShowAlerts {
            get {
                return ResourceManager.GetString("ShowAlerts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show Details.
        /// </summary>
        public static string ShowDetails {
            get {
                return ResourceManager.GetString("ShowDetails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show Map.
        /// </summary>
        public static string ShowMap {
            get {
                return ResourceManager.GetString("ShowMap", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SIM.
        /// </summary>
        public static string SIM {
            get {
                return ResourceManager.GetString("SIM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SOS.
        /// </summary>
        public static string Sos {
            get {
                return ResourceManager.GetString("Sos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sos Alert.
        /// </summary>
        public static string Sosalert {
            get {
                return ResourceManager.GetString("Sosalert", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Speed.
        /// </summary>
        public static string Speed {
            get {
                return ResourceManager.GetString("Speed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start.
        /// </summary>
        public static string Start {
            get {
                return ResourceManager.GetString("Start", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start Date.
        /// </summary>
        public static string StartDate {
            get {
                return ResourceManager.GetString("StartDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start Location.
        /// </summary>
        public static string StartLocation {
            get {
                return ResourceManager.GetString("StartLocation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start - Stop.
        /// </summary>
        public static string StartStop {
            get {
                return ResourceManager.GetString("StartStop", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Status.
        /// </summary>
        public static string Status {
            get {
                return ResourceManager.GetString("Status", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stoped Hours.
        /// </summary>
        public static string stopedhours {
            get {
                return ResourceManager.GetString("stopedhours", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stoping Vehicles.
        /// </summary>
        public static string StopingCars {
            get {
                return ResourceManager.GetString("StopingCars", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stoping Engine Off.
        /// </summary>
        public static string StopingCarsOff {
            get {
                return ResourceManager.GetString("StopingCarsOff", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stoping Engine On.
        /// </summary>
        public static string StopingCarsOn {
            get {
                return ResourceManager.GetString("StopingCarsOn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stop Location.
        /// </summary>
        public static string StopLocation {
            get {
                return ResourceManager.GetString("StopLocation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stopped Time.
        /// </summary>
        public static string StoppedTime {
            get {
                return ResourceManager.GetString("StoppedTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to System Settings.
        /// </summary>
        public static string System_Settings {
            get {
                return ResourceManager.GetString("System Settings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Take Of.
        /// </summary>
        public static string TakeOf {
            get {
                return ResourceManager.GetString("TakeOf", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tasks.
        /// </summary>
        public static string Tasks {
            get {
                return ResourceManager.GetString("Tasks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tasks Management.
        /// </summary>
        public static string Tasks_Management {
            get {
                return ResourceManager.GetString("Tasks Management", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Task Type.
        /// </summary>
        public static string TaskType {
            get {
                return ResourceManager.GetString("TaskType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The average speed.
        /// </summary>
        public static string Theaveragespeed {
            get {
                return ResourceManager.GetString("Theaveragespeed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Time passed after last log.
        /// </summary>
        public static string Timepassedafterlastlog {
            get {
                return ResourceManager.GetString("Timepassedafterlastlog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to To.
        /// </summary>
        public static string To {
            get {
                return ResourceManager.GetString("To", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Today.
        /// </summary>
        public static string Today {
            get {
                return ResourceManager.GetString("Today", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total Price.
        /// </summary>
        public static string TotalPrice {
            get {
                return ResourceManager.GetString("TotalPrice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to to the check point.
        /// </summary>
        public static string tothecheckpoint {
            get {
                return ResourceManager.GetString("tothecheckpoint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tracking Vehicles.
        /// </summary>
        public static string TrackingCars {
            get {
                return ResourceManager.GetString("TrackingCars", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Train Speed.
        /// </summary>
        public static string TrainSpeed {
            get {
                return ResourceManager.GetString("TrainSpeed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Turkish Name.
        /// </summary>
        public static string TurkishName {
            get {
                return ResourceManager.GetString("TurkishName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type of Alert.
        /// </summary>
        public static string TypeAlert {
            get {
                return ResourceManager.GetString("TypeAlert", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type of Alert.
        /// </summary>
        public static string TypeofAlert {
            get {
                return ResourceManager.GetString("TypeofAlert", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unit.
        /// </summary>
        public static string Unit {
            get {
                return ResourceManager.GetString("Unit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User Is In Active.
        /// </summary>
        public static string UserIsInActiveErrMsg {
            get {
                return ResourceManager.GetString("UserIsInActiveErrMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User Name.
        /// </summary>
        public static string UserName {
            get {
                return ResourceManager.GetString("UserName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User Not Found.
        /// </summary>
        public static string UserNotFoundErrMsg {
            get {
                return ResourceManager.GetString("UserNotFoundErrMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User or Password Is Wrong.
        /// </summary>
        public static string UserOrPasswordIsWrongErrMsg {
            get {
                return ResourceManager.GetString("UserOrPasswordIsWrongErrMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Users.
        /// </summary>
        public static string Users {
            get {
                return ResourceManager.GetString("Users", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Users Management.
        /// </summary>
        public static string Users_Management {
            get {
                return ResourceManager.GetString("Users Management", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Valid Logs.
        /// </summary>
        public static string ValidLogs {
            get {
                return ResourceManager.GetString("ValidLogs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vechile model.
        /// </summary>
        public static string Vechilemodel {
            get {
                return ResourceManager.GetString("Vechilemodel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vehicle.
        /// </summary>
        public static string Vehicle {
            get {
                return ResourceManager.GetString("Vehicle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vehicle Drivers.
        /// </summary>
        public static string VehicleDrivers {
            get {
                return ResourceManager.GetString("VehicleDrivers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vehicle Status.
        /// </summary>
        public static string VehicleStatus {
            get {
                return ResourceManager.GetString("VehicleStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vehicle Types .
        /// </summary>
        public static string VehicleTypes {
            get {
                return ResourceManager.GetString("VehicleTypes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vendor.
        /// </summary>
        public static string Vendor {
            get {
                return ResourceManager.GetString("Vendor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vendors.
        /// </summary>
        public static string Vendors {
            get {
                return ResourceManager.GetString("Vendors", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure , you want to delete this item ?.
        /// </summary>
        public static string WantToDelete {
            get {
                return ResourceManager.GetString("WantToDelete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Weekly.
        /// </summary>
        public static string Weekly {
            get {
                return ResourceManager.GetString("Weekly", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Weight.
        /// </summary>
        public static string Weight {
            get {
                return ResourceManager.GetString("Weight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Weight Before.
        /// </summary>
        public static string WeightBefore {
            get {
                return ResourceManager.GetString("WeightBefore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Weight Difference.
        /// </summary>
        public static string WeightDifference {
            get {
                return ResourceManager.GetString("WeightDifference", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Welcome.
        /// </summary>
        public static string Welcome {
            get {
                return ResourceManager.GetString("Welcome", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Work Shifts.
        /// </summary>
        public static string Work_Shifts {
            get {
                return ResourceManager.GetString("Work Shifts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Periods Of Work Shifts.
        /// </summary>
        public static string WorkShiftPeriods {
            get {
                return ResourceManager.GetString("WorkShiftPeriods", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Must Be Enter At Least One Period Of Work Shifts.
        /// </summary>
        public static string WorkShiftPeriodsValidation {
            get {
                return ResourceManager.GetString("WorkShiftPeriodsValidation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yearly.
        /// </summary>
        public static string Yearly {
            get {
                return ResourceManager.GetString("Yearly", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yes.
        /// </summary>
        public static string Yes {
            get {
                return ResourceManager.GetString("Yes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to yesterday.
        /// </summary>
        public static string yesterday {
            get {
                return ResourceManager.GetString("yesterday", resourceCulture);
            }
        }
    }
}
